# Generated by Django 5.2.6 on 2025-10-18 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PriceHistory',
            new_name='PriceHistoryD1',
        ),
    ]
