# Generated by Django 5.2.6 on 2025-10-19 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_pricehistoryd1_company_pricehistoryh1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PriceHistoryH4',
        ),
    ]
